### ISSUE TITLE
GuiOpenEvent

### ISSUE THREAD

**Issue by Blargerist** [way2muchnoise/BetterAchievements#11]
Thought I would point out a convenient alternative to some of the ASM. You appear to be using ASM in order to have your achievement gui be opened rather than the default MC achievement gui.

There is an event which is called whenever a gui is opened. A field in this event can be easily changed in order to have a custom gui open instead. 

```
@SubscribeEvent
public void onGuiOpen(final GuiOpenEvent e)
{
    if (e.gui instanceof GuiAchievements) //Check for the gui class you wish to replace
    {
        e.gui = new YourGui(); //Set the events "gui" field as your gui
    }
}
```

**Comment by way2muchnoise** [comment]
I didn't know about this, but will look into it.
