### ISSUE TITLE
Icon Bar & Description/Titles

### ISSUE THREAD

**Issue by rcistano** [way2muchnoise/BetterAchievements#12]
Some of the Icons on the Achievement Bar are missing.

![screenshot01](https://cloud.githubusercontent.com/assets/13685776/9690438/3709c600-52f1-11e5-987a-b3e96517cd70.jpg)

Also the achievement titles are not showing up.

**Comment by way2muchnoise** [comment]
Could you point out which mods those are?

**Comment by rcistano** [comment]
Blood Magic, Twilight Forest, HEE Challenges (not sure what mod this comes from)

**Comment by rcistano** [comment]
Why was this closed?

**Comment by way2muchnoise** [comment]
Because I fixed it :D

**Comment by rcistano** [comment]
oh, alright :) cant wait to get the new update.

**Comment by way2muchnoise** [comment]
Pushing it to CF right now so give it like 10 mins for them to accepts

**Comment by rcistano** [comment]
No problem, just glad I decided to give this mod a try. Makes it alot easier to check up on my achievements

**Comment by way2muchnoise** [comment]
Glad it can be helpful ^^
