### ISSUE TITLE
Unable to handle more than 9 tabs

### ISSUE THREAD

**Issue by AtomicBlom** [way2muchnoise/BetterAchievements#14]
First of all, very nice mod. I was talking to some friends about needing EXACTLY what your mod does.

I'm running your mod on a pack that includes 10 tabs of achievement, but unfortunately only the first 9 are available:
- Minecraft
- IndustrialCraft 2
- Blood Magic
- Botania
- Twilight Forest
- Mystcraft
- Pneumaticraft
- Applied Energistics 2
- Buildcraft
- TConstruct

The Tinker's construct tab is only available using the "old screen" option. Is there the possibility of adding a additional pages as per the Creative screen, or running a second set of tabs at the bottom?

Thanks,
Steven

**Comment by way2muchnoise** [comment]
This is what I have now @AtomicBlom, when your mouse is on the tabs and you scroll this happens
![](http://puu.sh/k1Z14/f19a263d7e.gif)
Any comments?

**Comment by BBoldt** [comment]
What if people don't have scroll wheels? :P 

maybe add a little arrow or something somewhere?

**Comment by AtomicBlom** [comment]
It's definitely an improvement it will tide me over.

But it's not really discoverable. I didn't think about using the mouse wheel before I reported the issue. I think using the same behaviour as the creative page (arrows either side, moving full pages at a time) would probably be the most pleasant experience for players.

**Comment by way2muchnoise** [comment]
I'll add arrows tonight

**Comment by way2muchnoise** [comment]
@BBoldt @AtomicBlom Buttons \o/ (also moves +/-9 tabs, while scrolling is +/-1 tab)
![](http://puu.sh/k2ZEU/3117f65db3.png)

**Comment by AtomicBlom** [comment]
Brilliant! Thanks for this mod, going to recommend it to a few map maker friends :D

**Comment by way2muchnoise** [comment]
Seems like everyone is pleased now. Will push a build somewhere later tonight (so with in lets say 2 hours from this post)
