### ISSUE TITLE
NBTExceptions

### ISSUE THREAD

**Issue by mrammy** [way2muchnoise/BetterAchievements#21]
Upon loading into a new world I get this http://hastebin.com/ihahubiviv.vbs. It doesn't seem to affect tab display as far as I can tell.

**Comment by way2muchnoise** [comment]
What is the content of the config? Also maybe I shouldn't print those. It is the Json to NBT conversion that fails most likely due to a bad config. The loader deals with it and catches exceptions, but I left the default `e.printStacktrace();` in place that is why it is spamming.

**Comment by mrammy** [comment]
Posting this here for reference purposes, because I already sent it to you on IRC. The url to what is in the config is http://hastebin.com/adiyecuvim.coffee. Perhaps the NBT is not contained in the config so it is returning null when it is looking for it there?
