### ISSUE TITLE
Look into porting to 1.9

### ISSUE THREAD

**Issue by way2muchnoise** [way2muchnoise/BetterAchievements#30]
If stable enough that is

**Comment by Prospector** [comment]
Have you asked at all about getting this into forge? IMO would be really nice to have built in.

**Comment by way2muchnoise** [comment]
As PRing stuff into forge takes a lot of effort I'm not that eager. The way the UI works would fit in but I don't know if forge would like all the extra features (colours, backgrounds) it adds. But if I have some time I'll see if I can get in contact with some people and see where I get.

**Comment by way2muchnoise** [comment]
Since there is an official release of forge and I have a build using it up on CF I4m going to call this done
