### ISSUE TITLE
Make achievements independent of each other

### ISSUE THREAD

**Issue by Tachytaenius** [way2muchnoise/BetterAchievements#32]
No need to remove the arrows that link achievements, but if they could be unlocked independent of each other I would love that. It's never nice beating the wither before the ender dragon but having to beat it again because you didn't do the achievements in order.

**Comment by way2muchnoise** [comment]
Been looking at that before see #26 , but I'll give it an other try soon

**Comment by Tachytaenius** [comment]
Great! Good luck.

**Comment by way2muchnoise** [comment]
You can go download a [test build from the drone.io server](https://drone.io/github.com/way2muchnoise/BetterAchievements/files) to test the unlocking.

It will unlock all previously done achievements once you unlock the ones that are needed to unlock it. (eg. beat wither -> get no achievement -> beat dragon -> get dragon and wither achievement)

**Comment by way2muchnoise** [comment]
Could test the latest build from the [drone.io server](https://drone.io/github.com/way2muchnoise/BetterAchievements/files) once more?

Everything should be implemented and saved per world now.

**Comment by Tachytaenius** [comment]
Oh nice, sure.

**Comment by Tachytaenius** [comment]
It doesn't seem to work. I was using Creative mode, and it didn't work in Biomes O' Plenty OR Minecraft's achievements area. I downloaded "BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar" and still it doesn't seem to work. If you need any more specs, ask me!

**Comment by way2muchnoise** [comment]
Well for now it was made for 1.9 guess I should back port it to 1.8.9 and maybe 1.7.10
