### ISSUE TITLE
BetterAchievements-1.9-0.2.0 crashes client on startup using forge build 1811

### ISSUE THREAD

**Issue by kreezxil** [way2muchnoise/BetterAchievements#33]
fml latest: http://paste.ee/p/ksdVV

crash report: http://paste.ee/p/FIAA0

**Comment by way2muchnoise** [comment]
Download the bleeding edge from the [build server](https://drone.io/github.com/way2muchnoise/BetterAchievements/files). I will release it on curse forge soon.
