### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by C0rn3j** [way2muchnoise/BetterAchievements#43]
Some mods are missing an icon(are those set on your end or do mod authors have to support your mod?).

Could you perhaps add a feature that if a mod is missing icon the first achievement is picked as one?

Mods that miss an icon: ArmorPlus, Abyssalcraft.

Modlist: http://pastebin.com/bbDEWk51

Server forge 2010, client 2014. 

http://i.imgur.com/m230VFZ.png

**Comment by way2muchnoise** [comment]
The feature you are asking for is already in. That is how the icons are chosen in the first place. I guess something is going wrong with the rendering. You could always set them yourself. There is a config for that. I'll leave this open and look into why they don't show.

**Comment by drakray** [comment]
Base Metal and Modern Metal achievement pages have this same issue, using forge 2066 and latest mod version of both
