### ISSUE TITLE
Disables achievement fireworks from endercore

### ISSUE THREAD

**Issue by freethought78** [way2muchnoise/BetterAchievements#50]
I know that many people don't like the fireworks that go off when achievements are completed which are added by EnderCore (previously ttcore), but I  like them so much that I use endercore in my game just for the achievement fireworks that they add, even though I don't use any of the mods that depend on endercore itself as a library. Achievements in minecraft are a cool way to have goals without using a questbook. BetterAchievements really improves upon the achievement interface in the game, but it makes the fireworks in endercore stop working. There is a setting in endercore (which oddly enough is also called "Better Achievements") which when turned on produces fireworks when you complete an achievement. I've double checked that the option is enabled in endercore. When I remove the better achievements mod from the game, the fireworks start working again. When I add better achievements back into the game, they stop working, even though the option is still enabled in endercore. Thanks in advance.

**Comment by ghost** [comment]
How to turn off that crap actually?
