### ISSUE TITLE
Larger Advancement screen messes up wrapping around to lower half of advancements

### ISSUE THREAD

**Issue by davqvist** [way2muchnoise/BetterAchievements#53]
MC 1.12.1
Forge 2446
Better Advancements 0.0.1.7

If more than those 8 Advancements in the top row open up, the bottom row gets started, but it is in the middle of the screen, rather than at the bottom, doesn't matter which GUI size. Not sure how to describe it better, do you need a screenshot?

**Comment by way2muchnoise** [comment]
I know the issue @darkosto told me about it on stream.

**Comment by way2muchnoise** [comment]
Also this is an issue of Better Advancements

**Comment by davqvist** [comment]
I didn't see you made another github for it, I figured you would keep the same. Fair enough. Sorry about that.

**Comment by way2muchnoise** [comment]
np man
